services:
  mariadb:
    image: mariadb
    container_name: mariadbb10
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: concesionario
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Concesionario.sql://docker-entrypoint-initdb.d/Concesionario.sql:ro
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb10
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
    ports:
      - 720:80
    depends_on:
      - mariadb
  python:
    build: ./api
    container_name: pythonb10
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: concesionario
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8090
      HOST: 0.0.0.0
    depends_on:
      - mariadb
  apache-waf:
    build: ./apache #./waf/ en un futuro
    ports:
      - 9100:80
    depends_on:
      - python
    links:
      - python
volumes:
  mariadb_data:
