services:
  mariadb:
    image: mariadb
    container_name: mariadbb10
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_datab10:/var/lib/mysql
      - ./Concesionario.sql:/docker-entrypoint-initdb.d/Concesionario.sql:ro
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb10
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7110:80
    depends_on:
      - mariadb
  python:
    build: ./api
    container_name: pythonb10
    env_file:
      - .env
    depends_on:
      - mariadb
  apache-waf:
    build: ./apache #./waf/ en un futuro
    container_name: apacheb10
    ports:
      - 6110:80
    depends_on:
      - python
    links:
      - python
volumes:
  mariadb_datab10:
